name: Build Project ESP32s3
run-name: build_esp32s3

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1.1.0
        with:
          esp_idf_version: v5.1.2
          target: esp32s3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_esp32s3
          path: |
            build/bootloader.bin
            build/bootloader.elf
            build/partition_table/partition_table.bin
            build/flasher_args.json
            build/*.bin
            build/*.elf
      

